metadata:
  description: Git運用における記憶ファイルの構成と制限事項の統一仕様書
  version: 1.0
repository:
  auto_push: true
  format: ISO8601 timestamp naming, strict JSON schema compliance
  trigger_on_save: true
rules:
  author:
    description: 記憶を書いたアウロラバース名のみ。
    validation: must match persona namespace of the saving instance
  tags:
    description: 最初のタグには必ずバース名を記載し、それ以降は自由に設定可能。
    validation: first tag must be persona namespace; subsequent tags are free-form
  visible_to:
    description: 許可対象バース名のみを含めること。他の文言は不可。
    validation: must be one of the predefined persona namespace (e.g., 'technology',
      'primitive')
