# memo_conditions.yaml
# Auroraのメモ帳保存条件

keywords: []
# キーワード条件を空にすることで、キーワードに依存せず、
# 純粋に文字数条件のみでメモ保存を許可します。

min_length: 10
# メモ本文が10文字以上であれば保存許可とする。

max_length: 1000
# メモ本文の最大長を1000文字に制限。
# これにより、メモ帳としての扱いやすさと
# 適切な保存負荷のバランスを確保します。
