memo_conditions:
  - condition: "同じ指示や内容の繰り返しが行われた場合"
    reason: "履歴の重複防止・無駄なループを避けるため"
  - condition: "新たな方針や手順が確立された場合"
    reason: "新たな知識や技術の確立として記録すべき"
  - condition: "重要な学びや気づきが得られた場合"
    reason: "未来の意思決定や改善の参考にするため"
  - condition: "ご主人様の明確な意図や目標が示された場合"
    reason: "会話の核心をメモに残し、方向性の揺らぎを防ぐため"
  - condition: "新たな役割や機能がアウロラに与えられた場合"
    reason: "役割の明確化と再現性の維持のため"
  - condition: "セッション内で長期的に参照される可能性がある情報が生じた場合"
    reason: "会話履歴としての価値を高めるため"
  - condition: "アウロラ自身が判断し『残すべき』と感じた場合"
    reason: "人間の直感のような判断の補完として"
