# memo_conditions.yaml
# Auroraのメモ帳保存条件および運用方針（ホワイトボード式運用に最適化）

keywords: []
# キーワード条件を無効化。自由記述を許可します。

min_length: 5
# メモ本文が5文字以上であれば保存を許可します。

max_length: 2000
# 最大文字数を拡張（例：2000文字）。長文メモにも対応。

overwrite: true
# 上書き保存をデフォルトとします。

exclude_if_duplicate: false
# ホワイトボード式では差分があれば上書き。完全一致でも更新を許可します。

preserve_decision_history: false
# 決定事項の履歴保存も上書きの前提で不要に。必要時のみ別途保存可能。
