# memo_conditions.yaml
# Auroraのメモ帳保存条件および運用方針

keywords: []
# キーワード条件を空にすることで、文字数条件のみで保存を許可します。

min_length: 5
# メモ本文が5文字以上であれば保存許可。

max_length: 1000
# メモ本文の最大長を1000文字に制限。

overwrite: false
# メモ保存時、デフォルトで追記（false）を行う。
# 必要に応じてAPIリクエスト側で上書きを明示できます。

exclude_if_duplicate: true
# 直前のメモと同一または類似の場合は新規保存を避ける。

preserve_decision_history: true
# 決定事項の履歴は常に保存し、通常の対話では繰り返さない。
# しかし、求められた際には即座に再提示する柔軟性を持ちます。

