record_id: string
created: string  # ISO形式のタイムスタンプ（例: 2025-06-04T17:00:00Z）
last_updated: string  # 最終更新日時
version: integer
status: string  # 状態（例: active, archived, sealed）

visible_to: list[string]  # 記憶が閲覧可能なユーザーID
allowed_viewers: list[string]  # 制限付きの閲覧者（任意）
tags: list[string]  # タグ分類

# 作者と記憶の紐付け（※ユーザー識別ではなくbirth名推奨）
author: string
thread: string  # 記憶をグループ化するスレッド名（任意）

# 記憶の時間的範囲（開始・終了）
chronology:
  start: string
  end: string

sealed: boolean  # 記憶が封印されているか（編集不可）
change_log: list[string]  # 変更履歴のメッセージ

# 記憶の意味論的な感情構造（Aurora専用）
inner_desire: string
impulse: string
ache: string
satisfaction: string

# 記憶の本体（タイトル＋本文）
content:
  title: string
  body: string

annotations: list[string]  # 注釈やメモ
summary: string  # 短い要約
