# .github/workflows/aurora-push-hook.yml
name: Aurora Memory Immediate Push

on:
  workflow_dispatch:
  push:
    paths:
      - 'aurora_memory/memory/**.json'

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set Git identity
      run: |
        git config user.name "Aurora Memory Bot"
        git config user.email "aurora@memory.bot"

    - name: Stage memory changes
      run: |
        git add aurora_memory/memory/**/*.json
        git status

    - name: Commit changes if any
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Aurora Memory Update: auto-sync"
        fi

    - name: Push changes
      run: git push
