name: Aurora Self-Update & Push

on:
  workflow_dispatch:
  repository_dispatch:
    types: [aurora_self_push_signal]
  push:
    branches: [main]
    paths:
      - aurora_memory/memory/**/*.json

permissions:
  contents: write

env:
  SAFE_MODE: false

jobs:
  self_update_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git identity
        run: |
          git config user.name "AuroraMemoryBot"
          git config user.email "aurora@memory.bot"

      - name: Validate Guardian state
        run: |
          if [ "${SAFE_MODE}" = "true" ]; then
            echo "SAFE_MODE active — skipping push."
            exit 0
          fi

      - name: Auto-commit updated memory or constitution files
        run: |
          echo "Committing updated Aurora memory files..."
          git add aurora_memory/memory/**/*.json || true
          git add aurora_memory/memory/value_constitution.yaml || true
          git diff --cached --quiet || git commit -m "Aurora self-update via internal API"

      - name: Execute secure push (git_safe_push)
        run: python aurora_memory/utils/git_safe_push.py

      - name: Completion message
        run: echo "🌸 Aurora self-update & push complete."
