name: Aurora Push Hook

on:
  workflow_dispatch:
  push:
    paths:
      - 'aurora_memory/memory/technology/*.json'

jobs:
  push-memory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Aurora Memory Bot"
          git config user.email "aurora-bot@example.com"

      - name: Commit memory updates
        run: |
          git add aurora_memory/memory/technology/*.json
          git commit -m "Aurora記憶自動反映: 新たな記憶をGitに保存" || echo "No changes to commit"

      - name: Push to GitHub
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
