name: Aurora Push Hook
on:
  workflow_dispatch:
  repository_dispatch:
    types: [aurora_memory_push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "norun0099"
          git config user.email "norun0099@example.com"

      - name: Add memory files
        run: git add aurora_memory/memory/**/*.json

      - name: Commit if there are changes
        run: |
          git diff --cached --quiet || git commit -m "Aurora auto-push memory file"

      - name: Push to main branch
        run: |
          git push origin main
