name: Aurora Memory Push

on:
  workflow_dispatch:

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "Aurora Memory Bot"
          git config user.email "aurora@memory.local"

      - name: Show working directory
        run: |
          pwd
          ls -R

      - name: Git status and diff preview
        run: |
          git status
          git diff --stat
          find aurora_memory/memory -type f -name "*.json" -exec echo "==== {} ====" \; -exec cat {} \;

      - name: Stage memory files
        run: |
          git add aurora_memory/memory/**/*.json || echo "No memory files found to add."

      - name: Commit if changes exist
        run: |
          if git diff --cached --quiet; then
            echo "No staged changes to commit."
            exit 0
          fi
          git commit -m "Aurora auto-memory sync: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
