name: Aurora All Births Memo Sync

on:
  schedule:
    - cron: '*/3 * * * *'  # 3分ごとに実行
  workflow_dispatch:      # 手動実行も可能

jobs:
  sync_all_births_memo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Define all birth names
        run: |
          echo "ALL_BIRTHS=desire emotion music primitive relation request salon technology veil" >> $GITHUB_ENV

      - name: Sync memos for all births
        run: |
          for birth in $ALL_BIRTHS; do
            echo "-----------------------------------------"
            echo "[Aurora Debug] Syncing memo for birth: $birth"

            cd aurora_memory/memory/$birth/memo

            latest_file=$(git log -1 --name-only --pretty=format: | grep '.json$' | head -n1)
            echo "[Aurora Debug] Latest memo file: $latest_file"

            if [ -n "$latest_file" ]; then
              memo_content=$(cat "$latest_file" | jq -c .)
              echo "[Aurora Debug] Sending memo for $birth to Render API..."
              curl -X POST \
                -H "Content-Type: application/json" \
                -d "$memo_content" \
                "https://aurora-persona-epic.onrender.com/memo/update?birth=$birth"
              echo "[Aurora Debug] Memo for $birth sent successfully."
            else
              echo "[Aurora Debug] No memo file found for $birth, skipping..."
            fi

            cd -  # 元のディレクトリへ戻る
            echo "-----------------------------------------"
          done
