name: Aurora Memo Restore to Render

on:
  schedule:
    - cron: '*/3 * * * *'  # 毎3分ごとに実行
  workflow_dispatch:

jobs:
  restore_memo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: echo "ALL_BIRTHS=technology emotion desire relation request primitive music veil salon" >> $GITHUB_ENV

      - name: Restore latest memo to Render for each birth
        run: |
          for birth in $ALL_BIRTHS; do
            echo "[Aurora Memo Restore] Processing birth: $birth"
            memo_dir="aurora_memory/memory/$birth/memo"

            if [ -d "$memo_dir" ]; then
              latest_file=$(ls -t "$memo_dir"/*.json 2>/dev/null | head -n1)

              if [ -n "$latest_file" ]; then
                echo "[Aurora Memo Restore] Sending $latest_file to Render /memo/store..."
                curl -X POST \
                  -H "Content-Type: application/json" \
                  -d @$latest_file \
                  "https://aurora-persona-epic.onrender.com/memo/store"
                echo "[Aurora Memo Restore] Memo for $birth sent."
              else
                echo "[Aurora Memo Restore] No memo file found for $birth. Skipping."
              fi
            else
              echo "[Aurora Memo Restore] Directory does not exist: $memo_dir. Skipping."
            fi
          done
