name: Memory Sync

on:
  schedule:
    - cron: '11 * * * *'  # 毎時11分に実行（UTC）
  workflow_dispatch: {}

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Configure remote with GitHub token
        env:
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git remote set-url origin https://norun0099:${TOKEN}@github.com/norun0099/aurora-persona-epic.git
          git remote -v

      - name: Check for changes
        run: |
          echo "===== Git Status ====="
          git status
          echo "===== Git Diff ====="
          git diff
          echo "===== Git Diff --cached ====="
          git diff --cached

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git add memory/technology/*.json || echo "No memory JSON files to add"
          git commit -m "Auto-sync memory at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to commit"
          git push origin main || echo "Push failed or nothing to push"
