name: Whiteboard Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: whiteboard-sync
  cancel-in-progress: true

jobs:
  sync_whiteboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "aurora@users.noreply.github.com"
          git config --global user.name "Aurora Sync Bot"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run whiteboard manager in sync mode
        run: python aurora_memory/utils/whiteboard_manager.py
